name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build with wasm-pack
        run: |
          cd Dapp/wasm-lib
          wasm-pack build --target web

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: |
          cd Dapp/webapp
          npm install

      - name: Build the web app
        run: |
          cd Dapp/webapp
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd Dapp/webapp
          mkdir -p public
          cp -r ../wasm-lib/pkg/* public/
          echo "my-dapp-wasm-lib" > public/CNAME
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
