[package]
name = "alloy-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.2", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.38.0", features = ["full"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-cli = "0.2.92"
